name: eletroufcg
channels:
  - conda-forge
dependencies:
  - python=3.12
  - dask-core=2025.5.1
  - dask=2025.5.1
  - exifread=3.3.1
  - h5py=3.14.0
  - holoviews=1.21.0
  - ipyaladin
  - ipykernel=6.29.5
  - ipynbname
  - ipywidgets=8.1.7
  - jupyter_bokeh
  - jupyter_server_terminals
  - jupyter_server=2.16.0
  - jupyter-server-proxy=4.4.0
  - jupyter=1.1.1
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - jupyterlab_widgets=3.0.15
  - jupyterlab-myst=2.4.2
  - jupyterlab=4.4.4
  - markdown-it-py=3.0.0
  - matplotlib-scalebar
  - matplotlib=3.10.3
  - mdit-py-plugins=0.4.2
  - mystmd==1.5.1
  - numpy=2.3.1
  - pandas=2.3.0
  - panel=1.7.2
  - pillow=11.3.0
  - pip
  - pydata-sphinx-theme=0.16.1
  - python-dotenv=1.1.1
  - pyviz_comms=3.0.6
  - rapidfuzz=3.13.0
  - reproject=0.14.1
  - rich=14.0.0
  - ruff=0.12.2
  - scikit-image=0.25.2
  - scikit-learn=1.7.0
  - scipy=1.16.0
  - selenium
  - sphinx-autodoc2=0.5.0
  - sphinx-book-theme=1.1.3
  - sphinx-copybutton=0.5.2
  - sphinx-design=0.6.1
  - sphinx-proof=0.1.3
  - sphinx-togglebutton=0.3.2
  - sphinx=8.2.3
  - sphinxcontrib-jsmath
  - sphinxcontrib-mermaid
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml=1.1.10
  - timezonefinder=6.5.9
  - tqdm=4.67.1
  - xarray=2025.7.0
  - pip:
      - sphinxcontrib-bibtex
      - opencv-python 
      - opencv-contrib-python
